//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaDeGestion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string email { get; set; }
        public string telefono { get; set; }
        public int estado { get; set; }
        public string descripcion { get; set; }
        public string destino { get; set; }
        public string origen { get; set; }
        public System.DateTime fechaSolicitud { get; set; }
        public Nullable<System.DateTime> fechaEntrega { get; set; }
        public string rutaFile { get; set; }
    }
}
